twitter:
  consumer_key: Ma7ngXmdzNtvkT6vMlV12w
  consumer_secret: m4JaE4NoxDty1spvgMWEe1DxilSTb9EA51G9TBgy08

facebook:
  consumer_key: 145321618939974
  consumer_secret: e34b5291ab3cbe6cfa9f59cce3116c34
